Update README.md
I updated d-apt repository link.
Replace vibe install command by dub install because
Jordi's APT repository does't provide ``vibe`` package.
Updated DMD version.

Any way ``./setup-linux.sh`` doesn't work on Debian Wheezy:
Error:
```
Building configuration "application", build type debug
Running dmd (compile)...
Error: Executable file not found: 

Run 'dub help' for usage information.
```